//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int ID { get; set; }
        public string ClientID { get; set; }
        public string ArticleRef { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<bool> IsInCart { get; set; }
    }
}
