//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAMILLE
    {
        public FAMILLE()
        {
            this.ARTICLEE = new HashSet<ARTICLEE>();
        }
    
        public string FA_CodeFamille { get; set; }
        public Nullable<short> FA_Type { get; set; }
        public string FA_Intitule { get; set; }
        public Nullable<short> FA_UniteVen { get; set; }
        public Nullable<decimal> FA_Coef { get; set; }
        public Nullable<short> FA_SuiviStock { get; set; }
        public Nullable<short> FA_Garantie { get; set; }
        public string FA_CodeFiscal { get; set; }
        public Nullable<short> FA_UnitePoids { get; set; }
        public Nullable<short> FA_Publie { get; set; }
    
        public virtual ICollection<ARTICLEE> ARTICLEE { get; set; }
    }
}
