//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_Commerce2Entities4 : DbContext
    {
        public E_Commerce2Entities4()
            : base("name=E_Commerce2Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICLEE> ARTICLEE { get; set; }
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<FAMILLE> FAMILLE { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
    }
}
