//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ARTICLE
    {
        public F_ARTICLE()
        {
            this.F_ARTICLE1 = new HashSet<F_ARTICLE>();
        }
    
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public string AR_Design { get; set; }
        public byte[] cbAR_Design { get; set; }
        public string FA_CodeFamille { get; set; }
        public byte[] cbFA_CodeFamille { get; set; }
        public string AR_Substitut { get; set; }
        public byte[] cbAR_Substitut { get; set; }
        public string AR_Raccourci { get; set; }
        public byte[] cbAR_Raccourci { get; set; }
        public Nullable<short> AR_Garantie { get; set; }
        public Nullable<short> AR_UnitePoids { get; set; }
        public Nullable<decimal> AR_PoidsNet { get; set; }
        public Nullable<decimal> AR_PoidsBrut { get; set; }
        public Nullable<short> AR_UniteVen { get; set; }
        public Nullable<decimal> AR_PrixAch { get; set; }
        public Nullable<decimal> AR_Coef { get; set; }
        public Nullable<decimal> AR_PrixVen { get; set; }
        public Nullable<short> AR_PrixTTC { get; set; }
        public Nullable<short> AR_Gamme1 { get; set; }
        public Nullable<short> AR_Gamme2 { get; set; }
        public Nullable<short> AR_SuiviStock { get; set; }
        public Nullable<short> AR_Nomencl { get; set; }
        public string AR_Stat01 { get; set; }
        public string AR_Stat02 { get; set; }
        public string AR_Stat03 { get; set; }
        public string AR_Stat04 { get; set; }
        public string AR_Stat05 { get; set; }
        public Nullable<short> AR_Escompte { get; set; }
        public Nullable<short> AR_Delai { get; set; }
        public Nullable<short> AR_HorsStat { get; set; }
        public Nullable<short> AR_VteDebit { get; set; }
        public Nullable<short> AR_NotImp { get; set; }
        public Nullable<short> AR_Sommeil { get; set; }
        public string AR_Langue1 { get; set; }
        public string AR_Langue2 { get; set; }
        public string AR_EdiCode { get; set; }
        public byte[] cbAR_EdiCode { get; set; }
        public string AR_CodeBarre { get; set; }
        public byte[] cbAR_CodeBarre { get; set; }
        public string AR_CodeFiscal { get; set; }
        public string AR_Pays { get; set; }
        public string AR_Frais01FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais01FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais01FR_Rem03REM_Type { get; set; }
        public string AR_Frais02FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais02FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais02FR_Rem03REM_Type { get; set; }
        public string AR_Frais03FR_Denomination { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> AR_Frais03FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> AR_Frais03FR_Rem03REM_Type { get; set; }
        public Nullable<short> AR_Condition { get; set; }
        public Nullable<decimal> AR_PUNet { get; set; }
        public Nullable<short> AR_Contremarque { get; set; }
        public Nullable<short> AR_FactPoids { get; set; }
        public Nullable<short> AR_FactForfait { get; set; }
        public Nullable<System.DateTime> AR_DateCreation { get; set; }
        public Nullable<short> AR_SaisieVar { get; set; }
        public Nullable<short> AR_Transfere { get; set; }
        public Nullable<short> AR_Publie { get; set; }
        public Nullable<System.DateTime> AR_DateModif { get; set; }
        public string AR_Photo { get; set; }
        public Nullable<decimal> AR_PrixAchNouv { get; set; }
        public Nullable<decimal> AR_CoefNouv { get; set; }
        public Nullable<decimal> AR_PrixVenNouv { get; set; }
        public Nullable<System.DateTime> AR_DateApplication { get; set; }
        public Nullable<decimal> AR_CoutStd { get; set; }
        public Nullable<decimal> AR_QteComp { get; set; }
        public Nullable<decimal> AR_QteOperatoire { get; set; }
        public Nullable<int> CO_No { get; set; }
        public Nullable<int> cbCO_No { get; set; }
        public Nullable<short> AR_Prevision { get; set; }
        public Nullable<int> CL_No1 { get; set; }
        public Nullable<int> cbCL_No1 { get; set; }
        public Nullable<int> CL_No2 { get; set; }
        public Nullable<int> cbCL_No2 { get; set; }
        public Nullable<int> CL_No3 { get; set; }
        public Nullable<int> cbCL_No3 { get; set; }
        public Nullable<int> CL_No4 { get; set; }
        public Nullable<int> cbCL_No4 { get; set; }
        public Nullable<short> AR_Type { get; set; }
        public string RP_CodeDefaut { get; set; }
        public Nullable<short> AR_Nature { get; set; }
        public Nullable<short> AR_DelaiFabrication { get; set; }
        public Nullable<short> AR_NbColis { get; set; }
        public Nullable<short> AR_DelaiPeremption { get; set; }
        public Nullable<short> AR_DelaiSecurite { get; set; }
        public Nullable<short> AR_Fictif { get; set; }
        public Nullable<short> AR_SousTraitance { get; set; }
        public Nullable<short> AR_TypeLancement { get; set; }
        public Nullable<short> AR_Cycle { get; set; }
        public Nullable<short> AR_Criticite { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
        public Nullable<System.DateTime> C1ère_commercialisation { get; set; }
        public string Marque_commerciale { get; set; }
        public Nullable<decimal> Objectif___Qtés_vendues { get; set; }
        public Nullable<decimal> Pourcentage_teneur_en_or { get; set; }
    
        public virtual F_FAMILLE F_FAMILLE { get; set; }
        public virtual ICollection<F_ARTICLE> F_ARTICLE1 { get; set; }
        public virtual F_ARTICLE F_ARTICLE2 { get; set; }
    }
}
