//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_F
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_FAMILLE
    {
        public F_FAMILLE()
        {
            this.F_ARTICLE = new HashSet<F_ARTICLE>();
        }
    
        public string FA_CodeFamille { get; set; }
        public byte[] cbFA_CodeFamille { get; set; }
        public Nullable<short> FA_Type { get; set; }
        public string FA_Intitule { get; set; }
        public byte[] cbFA_Intitule { get; set; }
        public Nullable<short> FA_UniteVen { get; set; }
        public Nullable<decimal> FA_Coef { get; set; }
        public Nullable<short> FA_SuiviStock { get; set; }
        public Nullable<short> FA_Garantie { get; set; }
        public string FA_Central { get; set; }
        public byte[] cbFA_Central { get; set; }
        public string FA_Stat01 { get; set; }
        public string FA_Stat02 { get; set; }
        public string FA_Stat03 { get; set; }
        public string FA_Stat04 { get; set; }
        public string FA_Stat05 { get; set; }
        public string FA_CodeFiscal { get; set; }
        public string FA_Pays { get; set; }
        public Nullable<short> FA_UnitePoids { get; set; }
        public Nullable<short> FA_Escompte { get; set; }
        public Nullable<short> FA_Delai { get; set; }
        public Nullable<short> FA_HorsStat { get; set; }
        public Nullable<short> FA_VteDebit { get; set; }
        public Nullable<short> FA_NotImp { get; set; }
        public string FA_Frais01FR_Denomination { get; set; }
        public Nullable<decimal> FA_Frais01FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> FA_Frais01FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> FA_Frais01FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> FA_Frais01FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> FA_Frais01FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> FA_Frais01FR_Rem03REM_Type { get; set; }
        public string FA_Frais02FR_Denomination { get; set; }
        public Nullable<decimal> FA_Frais02FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> FA_Frais02FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> FA_Frais02FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> FA_Frais02FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> FA_Frais02FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> FA_Frais02FR_Rem03REM_Type { get; set; }
        public string FA_Frais03FR_Denomination { get; set; }
        public Nullable<decimal> FA_Frais03FR_Rem01REM_Valeur { get; set; }
        public Nullable<short> FA_Frais03FR_Rem01REM_Type { get; set; }
        public Nullable<decimal> FA_Frais03FR_Rem02REM_Valeur { get; set; }
        public Nullable<short> FA_Frais03FR_Rem02REM_Type { get; set; }
        public Nullable<decimal> FA_Frais03FR_Rem03REM_Valeur { get; set; }
        public Nullable<short> FA_Frais03FR_Rem03REM_Type { get; set; }
        public Nullable<short> FA_Contremarque { get; set; }
        public Nullable<short> FA_FactPoids { get; set; }
        public Nullable<short> FA_FactForfait { get; set; }
        public Nullable<short> FA_Publie { get; set; }
        public string FA_RacineRef { get; set; }
        public string FA_RacineCB { get; set; }
        public Nullable<int> CL_No1 { get; set; }
        public Nullable<int> cbCL_No1 { get; set; }
        public Nullable<int> CL_No2 { get; set; }
        public Nullable<int> cbCL_No2 { get; set; }
        public Nullable<int> CL_No3 { get; set; }
        public Nullable<int> cbCL_No3 { get; set; }
        public Nullable<int> CL_No4 { get; set; }
        public Nullable<int> cbCL_No4 { get; set; }
        public Nullable<short> FA_Nature { get; set; }
        public Nullable<short> FA_NbColis { get; set; }
        public Nullable<short> FA_SousTraitance { get; set; }
        public Nullable<short> FA_Fictif { get; set; }
        public Nullable<short> FA_Criticite { get; set; }
        public Nullable<short> cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public Nullable<System.DateTime> cbModification { get; set; }
        public Nullable<int> cbReplication { get; set; }
        public Nullable<short> cbFlag { get; set; }
    
        public virtual ICollection<F_ARTICLE> F_ARTICLE { get; set; }
    }
}
