//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_F
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIJOUEntities : DbContext
    {
        public BIJOUEntities()
            : base("name=BIJOUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<F_ARTICLE> F_ARTICLE { get; set; }
        public virtual DbSet<F_FAMILLE> F_FAMILLE { get; set; }
    }
}
